FROM amazonlinux:2023

# Atualizar pacotes e instalar Python e pip
RUN yum update -y && \
    yum install -y python3 python3-pip zip

# Criar diretório para a layer
WORKDIR /lambda-layer/python

# Instalar 'requests' no diretório correto
RUN python3 -m pip install requests -t .

# Compactar o conteúdo em layer.zip
WORKDIR /lambda-layer
RUN zip -r layer.zip python
